### ISSUE TITLE
error

### ISSUE THREAD

**Issue by XDqrkneZ** [WetABQ/BossBarAPI-Nukkit#2]
20:58:41 [CRITICAL] Could not execute taskHandler 16: eid
20:58:41 [ALERT] java.lang.RuntimeException: java.lang.NoSuchFieldError: eid
        at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:298)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:276)
        at cn.nukkit.Server.tick(Server.java:1082)
        at cn.nukkit.Server.tickProcessor(Server.java:848)
        at cn.nukkit.Server.start(Server.java:825)
        at cn.nukkit.Server.<init>(Server.java:508)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.NoSuchFieldError: eid
        at top.dreamcity.bossbarapi.BossBarAPI.addBossBar(BossBarAPI.java:89)
        at mcpe.plugin.Zen.TaskReset.onRun(TaskReset.java:31)
        at cn.nukkit.scheduler.Task.run(Task.java:51)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:295)
        ... 6 more

**Comment by WetABQ** [comment]
This plugin is no longer updated. In the latest version of Nukkit, use player.createBossbar,thanks
